package com.example.s_vote.navigation

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val HOME = "home"
    const val RESULT = "result"
    const val POLL_HISTORY = "poll_history"
    const val PROFILE = "profile"
    const val PROFILE_SETUP = "profile_setup"
    const val EDIT_PROFILE = "edit_profile"
    const val REGISTRATION = "registration"
    const val FORGOT_PASSWORD = "forgot_password"
    const val SCAN_ID = "scan_id/{candidateId}?position={position}"
    const val CANDIDATE_LIST_BASE = "candidate_list"
    const val CANDIDATE_LIST = "candidate_list/{roleName}"
    const val CANDIDATE_DETAIL = "candidate_detail/{id}"
    const val ADMIN_HOME = "admin_home"
    const val MANIFESTO = "manifesto"
    const val FAQ = "faq"
    const val VOTE_CONFIRMATION = "vote_confirmation/{candidateId}?position={position}&name={name}&dept={dept}&id={id}"
    const val VOTE_SUBMITTED = "vote_submitted"
    const val REPORTS = "reports"
    const val CREATE_ELECTION = "create_election"
    const val ADMIN_RECENT_CANDIDATES = "admin_recent_candidates"
    const val CANDIDATE_DASHBOARD = "candidate_dashboard/{candidateId}"
    const val CANDIDATE_PROFILE = "candidate_profile/{candidateId}"
    const val EDIT_CANDIDATE_PROFILE = "edit_candidate_profile/{candidateId}"
    const val CANDIDATE_FEEDBACK = "candidate_feedback/{candidateId}"
    const val CAMPAIGN_PREVIEW = "campaign_preview/{candidateId}"
    const val MANAGE_CANDIDATES = "manage_candidates"
    const val ADMIN_RESULTS_BASE = "admin_results"
    const val ADMIN_RESULTS = "admin_results/{electionId}" 
    const val ADMIN_ELECTION_LIST = "admin_election_list"
    const val ID_VERIFIED = "id_verified/{candidateId}?name={name}&dept={dept}&id={id}&position={position}"
    const val CANDIDATE_APPLICATION = "candidate_application/{userId}"
    const val APPLICATION_SUBMITTED = "application_submitted/{appId}"
    const val APPLICATION_STATUS = "application_status/{appId}"
    const val SUBSCRIPTION = "subscription/{userId}/{role}"
    const val ADMIN_CANDIDATE_REVIEW = "admin_candidate_review/{candidateId}"
    const val ADMIN_STUDENT_LIST = "admin_student_list"
    const val ADMIN_CANDIDATE_LIST = "admin_candidate_list"
    const val ADMIN_STUDENT_DETAIL = "admin_student_detail/{userId}"
    const val NOTIFICATIONS = "notifications"
    const val ELECTION_DETAIL = "election_detail/{electionId}"

    fun adminResults(electionId: String) = "admin_results/$electionId"

    fun candidateDetail(id: String) = "candidate_detail/$id"
    fun applicationStatus(appId: String) = "application_status/$appId"
    fun applicationSubmitted(appId: String) = "application_submitted/$appId"
    fun candidateDashboard(candidateId: String) = "candidate_dashboard/$candidateId"
    fun manageCandidateProfile(candidateId: String) = "candidate_profile/$candidateId"
    fun viewAllFeedback(candidateId: String) = "candidate_feedback/$candidateId"
    fun campaignPreview(candidateId: String) = "campaign_preview/$candidateId"
    fun voteConfirmation(candidateId: String, position: String, name: String, dept: String, id: String) = "vote_confirmation/$candidateId?position=$position&name=$name&dept=$dept&id=$id"
    fun adminCandidateReview(id: String) = "admin_candidate_review/$id"
    fun adminStudentDetail(id: String) = "admin_student_detail/$id"
}
