package com.example.s_vote.ocr

object CollegeList {

    val colleges = listOf(
        "SAVEETHA DENTAL COLLEGE AND HOSPITAL",
        "SAVEETHA MEDICAL COLLEGE AND HOSPITAL",
        "SAVEETHA ENGINEERING COLLEGE (AUTONOMOUS)",
        "SAVEETHA SCHOOL OF ENGINEERING",
        "SAVEETHA SCHOOL OF LAW",
        "SAVEETHA SCHOOL OF MANAGEMENT",
        "SAVEETHA COLLEGE OF PHYSIOTHERAPY",
        "SAVEETHA COLLEGE OF NURSING",
        "SAVEETHA COLLEGE OF ALLIED HEALTH SCIENCES",
        "SAVEETHA COLLEGE OF OCCUPATIONAL THERAPY",
        "SAVEETHA COLLEGE OF PHARMACY",
        "SAVEETHA COLLEGE OF LIBERAL ARTS AND SCIENCES",
        "SAVEETHA COLLEGE OF ARCHITECTURE AND DESIGN",
        "SAVEETHA SCHOOL OF PHYSICAL EDUCATION"
    )
}
